name: Slack Notification from External Trigger

on:
  repository_dispatch:
    types: [send_slack_alert] # 이벤트 이름 정의

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Post text to a Slack channel
        uses: slackapi/slack-github-action@v3.0.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ github.event.channel }}
            text: "✅ TEST 🆗 \n\n *GitHub 알림*\n*내용:* ${{ github.event.client_payload.message }}\n*발송자:* ${{ github.event.client_payload.sender }}"
